# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.network "private_network", ip: "192.168.11.11"
  config.vm.hostname = "node1"
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "plays/init.yml"
  end
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end
  
  
end
