---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: queue-master
  namespace: sock-shop
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: queue-master

  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
    
