name: Terraform Apply

on:
  pull_request:
    types:
      - closed

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infrastructure/

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.SA_KEY }}
        project_id: gd-gcp-gridu-devops-t1-t2
        export_default_credentials: true

    - name: Initialize Terraform
      run: terraform init

    - name: Apply Terraform changes
      run: terraform apply -auto-approve